[project]
name = "karlbench"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "blkinfo>=0.2.0",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "plumbum>=1.9.0",
    "psutil>=7.0.0",
]
